# -*- coding: utf-8 -*-

ALERT_LOW = 'low'
ALERT_MEDIUM = 'medium'
ALERT_HIGH = 'high'
ALERT_OVERSPEED = 'overspeed_start'
RELEVANT_ALERT_TYPES = [ALERT_LOW, ALERT_MEDIUM, ALERT_HIGH, ALERT_OVERSPEED]
