# Generated by Django 5.1.3 on 2024-12-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('app', '0023_device_event_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='device',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='device',
        ),
        migrations.RemoveField(
            model_name='event',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='event',
            name='car',
        ),
        migrations.RemoveField(
            model_name='event',
            name='key',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='car',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='key',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='parent_trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.CreateModel(
            name='EventSummary',
            fields=[
            ],
            options={
                'verbose_name': 'event summary',
                'verbose_name_plural': 'event summaries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.event',),
        ),
        migrations.CreateModel(
            name='TripSummary',
            fields=[
            ],
            options={
                'verbose_name': 'trip summary',
                'verbose_name_plural': 'trip summaries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.trip',),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
