# Generated by Django 5.1.3 on 2024-11-27 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_carrepair'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itp', models.TextField()),
                ('itp_date', models.DateTimeField()),
                ('road_tax', models.TextField()),
                ('road_tax_date', models.DateTimeField()),
                ('insurance', models.TextField()),
                ('insurance_date', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='app.car')),
            ],
        ),
    ]
