# Generated by Django 5.1.3 on 2024-11-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_carreminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreminder',
            name='car',
        ),
    ]
