# Generated by Django 5.1.3 on 2024-11-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_carreminder_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreminder',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='app.car'),
            preserve_default=False,
        ),
    ]
