# Generated by Django 5.1.3 on 2024-11-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_carreminder_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreminder',
            name='created_by',
        ),
    ]
