# Generated by Django 5.1.3 on 2024-11-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_carreminder_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarReminder',
        ),
    ]
