# Generated by Django 5.1.3 on 2024-12-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_carclass_location_car_registration_number_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_location',
        ),
        migrations.AddField(
            model_name='booking',
            name='drop_off_location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_location',
            field=models.CharField(max_length=255),
        ),
    ]
