# Generated by Django 5.1.3 on 2024-12-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_booking_user_booking_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='car_class',
        ),
    ]
