# Generated by Django 5.1.3 on 2024-12-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_carmodel_car_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='registration_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
