# Generated by Django 5.1.3 on 2024-12-05 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_carmodel_registration_number_alter_carmodel_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarClass',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='drop_off_location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_ending', to='app.location', verbose_name='Drop-off location'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_starting', to='app.location', verbose_name='Pick up location'),
        ),
        migrations.AlterField(
            model_name='key',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='county',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
