# Generated by Django 5.1.3 on 2024-12-05 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_carclass_remove_booking_drop_off_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_ending', to='app.location', verbose_name='Drop-off location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(choices=[('alfaromeo', 'Alfa Romeo'), ('audi', 'Audi'), ('bentley', 'Bentley'), ('bmw', 'BMW'), ('buick', 'Buick'), ('byd', 'BYD'), ('cadillac', 'Cadillac'), ('caterham', 'Caterham'), ('chevrolet', 'Chevrolet'), ('chrysler', 'Chrysler'), ('citroen', 'Citroen'), ('dacia', 'Dacia'), ('daewoo', 'Daewoo'), ('daihatsu', 'Daihatsu'), ('dodge', 'Dodge'), ('fiat', 'Fiat'), ('ford', 'Ford'), ('fso', 'FSO'), ('honda', 'Honda'), ('hyundai', 'Hyundai'), ('infinity', 'Infinity'), ('iveco', 'Iveco'), ('jaguar', 'Jaguar'), ('jeep', 'Jeep'), ('kia', 'Kia'), ('lada', 'Lada'), ('lancia', 'Lancia'), ('landrover', 'Land Rover'), ('lexus', 'Lexus'), ('mazda', 'Mazda'), ('mercedesbenz', 'Mercedes-Benz'), ('mia', 'Mia'), ('mini', 'Mini'), ('mitsubishi', 'Mitsubishi'), ('nissan', 'Nissan'), ('opel', 'Opel'), ('peugeot', 'Peugeot'), ('porsche', 'Porsche'), ('qoros', 'Qoros'), ('renault', 'Renault'), ('saab', 'Saab'), ('seat', 'SEAT'), ('skoda', 'Skoda'), ('smart', 'Smart'), ('ssangyong', 'Ssangyong'), ('subaru', 'Subaru'), ('suzuki', 'Suzuki'), ('tata', 'Tata'), ('tesla', 'Tesla'), ('toyota', 'Toyota'), ('volkswagen', 'Volkswagen'), ('volvo', 'Volvo')], default='BMW', max_length=12),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='current_type',
            field=models.CharField(blank=True, choices=[('ac', 'AC'), ('dc', 'DC')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine',
            field=models.CharField(choices=[('cng', 'CNG'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('gasoline', 'Gasoline'), ('hybrid', 'Hybrid'), ('other', 'Other')], default='electric', max_length=8),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.PositiveIntegerField(default='2020'),
        ),
    ]
