# Generated by Django 5.1.3 on 2024-12-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_booking_end_location_alter_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='engine_type',
            field=models.CharField(choices=[('cng', 'CNG'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('gasoline', 'Gasoline'), ('hybrid', 'Hybrid'), ('other', 'Other')], default='electric', max_length=8),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine',
            field=models.PositiveIntegerField(default='1396'),
        ),
    ]
