# Generated by Django 5.1.3 on 2024-12-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_carmodel_engine_type_alter_carmodel_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='latest_operation',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('pickup', 'Pick up'), ('putback', 'Put back')], editable=False, max_length=7),
        ),
        migrations.AlterField(
            model_name='key',
            name='latest_status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('ended', 'Ended'), ('valid', 'Valid')], editable=False, max_length=9),
        ),
    ]
