# Generated by Django 5.1.3 on 2024-12-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_key_latest_operation_alter_key_latest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyhistory',
            name='operation',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('pickup', 'Pick up'), ('putback', 'Put back')], max_length=7),
        ),
        migrations.AlterField(
            model_name='keyhistory',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('ended', 'Ended'), ('valid', 'Valid')], max_length=9),
        ),
    ]
