# Generated by Django 5.1.3 on 2024-12-12 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_device_event_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='app.location', verbose_name='current location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='app.carmodel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(default='', max_length=17),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
