# Generated by Django 5.1.3 on 2024-12-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_delete_driver_driver_alter_contract_driver_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='user_id',
            new_name='contractor_id',
        ),
    ]
