# Generated by Django 5.1.3 on 2024-12-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rename_user_id_contract_contractor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contractor_id',
            new_name='contractor',
        ),
    ]
